### ISSUE TITLE
As an end-user I would like to receive proper error messages in case something is not properly working

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#11]
Error situations that have to be considered are e.g.:
- [x] Issues in the interface with the Open Data Hub
- [x] Config files not available / not properly formatted

The user story includes following tasks:
- [x] GUI proposal -> @etomsen 
- [x] GUI review -> @rcavaliere 
- [x] Error handling by the front-end application -> @etomsen

**Comment by sh-olmedo** [comment]
Here let the mockup for the generic error:

![6-E2E - Desktop - fullscreen - error](https://user-images.githubusercontent.com/65165684/98138326-45985800-1ec3-11eb-9c69-838752d96bb6.png)

We need to know how to proceed when we receive the data of 22 but for the inter-urban don't get the complete info

Here you can find the mockups updated in [inVision](https://solhea.invisionapp.com/console/share/4Q1N9VDYPE)

**Comment by rcavaliere** [comment]
@sh-olmedo it's a little bit too generic, since we can have different situations, e.g.:
- [ ] data non available
- [ ] service offline
In my opinion we should provide the proper error message for each of the major error situations we can face

**Comment by etomsen** [comment]
done. plz test in the next version
