### ISSUE TITLE
As an end-user story I would like to see the timestamp associated to the data displayed through the application

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#12]
Data of each LinkStation has its correspondent timestamp.
Following logic has to be implemented: 
- [x] if the data associated to a LinkStation is old (e.g. not of the current day) -> this should be properly displayed
- [x] only one timestamp for each search has to be displayed. The timestamp to be displayed is the one referred to the last LinkStation of the travel chain 

The user story includes following tasks:
- [x] GUI proposal -> @etomsen 
- [x] GUI review -> @rcavaliere 
- [ ] Functionality implementation -> @etomsen

**Comment by sh-olmedo** [comment]
Here let the mockup:

![6-E2E - Desktop - fullscreen - Route 22 - origin list - destination map](https://user-images.githubusercontent.com/65165684/98137946-de7aa380-1ec2-11eb-9cfa-dd95ab919b1f.png)


Here you can find the prototype update in [inVision](https://solhea.invisionapp.com/console/share/4Q1N9VDYPE)

**Comment by rcavaliere** [comment]
That's fine!

**Comment by etomsen** [comment]
implemented
