### ISSUE TITLE
Open Data Hub interface implementation

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#2]
Tasks to do
- [x] Interface with ODH implemented
- [x] First web-component container created
- [x] Visualization of Bluetooth data 
- [x] Visualization of LinkStation data (A22, alternative roads) -> implement also integration of geometries from edge method, @rcavaliere makes an example of geometry for an A22 LinkStation

**Comment by rcavaliere** [comment]
@Piiit implements a smart way to provide access to LinkStation measurements and shares all details to @etomsen

**Comment by Piiit** [comment]
@etomsen @rcavaliere We have updated the data access rules and I have created a client ID/secret in keycloak.
If it is OK for you, we could share these information with our passbolt server: https://passwords.testingmachine.eu

Would that be OK for you?

**Comment by Piiit** [comment]
@etomsen As soon as you have the client_secret you can test it with

```sh
curl --location --request POST 'https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/token' \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode 'grant_type=client_credentials' \
    --data-urlencode 'client_id=it.bz.opendatahub.webcomponents.mobility-traffic' \
    --data-urlencode 'client_secret=tops3cret1234567890'
```

**Comment by etomsen** [comment]
> Would that be OK for you?

Yes, certo

**Comment by etomsen** [comment]
@Piiit avresti un messenger/skype? via [telegram](https://t.me/daubihe)?

**Comment by Piiit** [comment]
@rcavaliere We shared all needed data, and had a talk to about how to implement authentication... @etomsen will start to implement the auth workflow now

**Comment by Piiit** [comment]
@rcavaliere I move it to done in our kanban, so we know that our part is finished

**Comment by etomsen** [comment]
all done
