### ISSUE TITLE
As an end-user I would like to see a unique font in the texts displayed on the web-component

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#20]
At the moment, it is not the case. The texts appear to have multiple fonts. This should be part of the final graphical / usability fine tuning work of the web component

**Comment by etomsen** [comment]
Roberto, could you plz indicate where do you see the differences? A
screenshot could help

**Comment by rcavaliere** [comment]
@etomsen you can take one of those uploaded for other user stories. In particular, the text "last sync" appears to have a different font.

**Comment by etomsen** [comment]
@rcavaliere oki, I'll fix that one and the through the app. if you find any other plz, post it here

**Comment by etomsen** [comment]
I've fixed that particular issue with "last sync", but as we decided to drop the global css (that if present, has to be included on the page),  and the styles of the components inside the app are incapsulated, there is no good way of styling ALL the text in one shot. @rcavaliere to test in next release

**Comment by rcavaliere** [comment]
Agree. Let's close this together with #18
