### ISSUE TITLE
Complex link stations should be somewhere defined in terms of ordered list of "simple" link stations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#21]
See example in the screenshot: the list is not the correct one. Probably we need a config file in which all this is defined?
![Screenshot from 2020-11-10 22-11-25](https://user-images.githubusercontent.com/9825179/98734152-dbd7ec80-23a1-11eb-8f86-337962e2a904.png)

**Comment by etomsen** [comment]
Im already taking this from the config, but maybe its not the correct one.
Could you plz attach the list of cortect l8nk stations for both directions
(or specify what is wrong in this one)

**Comment by rcavaliere** [comment]
@etomsen in this case we should have, in the following order:
- Torricelli ->siemens
- siemens->Galilei_Palermo
- Galilei_Palermo -> Galilei_Lancia
- Galilei_Lancia -> Galilei_Virgolo
- Galilei_Virgolo -> Galleria_Virgolo
- Galleria_Virgolo ->P_Campiglio

**Comment by etomsen** [comment]
Ok, ill check it out.

**Comment by etomsen** [comment]
was connected to the fact if you ask api for the link stations with "in" selector by id, the original order of ids is not preserved. fixed on the client side. @rcavaliere to test in the next release

**Comment by rcavaliere** [comment]
OK. Is this hardcoded somewhere in the code, or do you use a config file?

**Comment by etomsen** [comment]
it's not exactly the config (because any config would be bundled into a component javascript), but an external json file that will need to be placed on server together with other assets. This json is loaded as an external resource via http call every user asks for data type, so it could be updated without updating the app. I've just implemented this.

**Comment by etomsen** [comment]
implementation finished. plz test
