### ISSUE TITLE
As an end-user I would expect to see the complete map

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#22]
See screenshot attached. Appears only if you see the web-component in an external window, both on Firefox and on Chrome.
![Screenshot from 2020-11-10 22-13-54](https://user-images.githubusercontent.com/9825179/98734474-4557fb00-23a2-11eb-9b29-68b42d152a2b.png)

**Comment by etomsen** [comment]
This will be hard to fix, as its only appearing in the webcomponent store
and only in full-screen mode and it does not report any error. Ive tried to
reproduce it locally but without a success for now... on a dedicated apache
server its functioning properly.

**Comment by rcavaliere** [comment]
@Piiit do you have an idea about the reason why it appears like that?

**Comment by etomsen** [comment]
I think, it's connected with some browser optimisation within the exact layout that is used in the full-screen version of the store. After the screen resize the error disappears. So from my side I could make a forced repaint/size recalculation on start, same way it's working on window resize. Let's see if it helps.

**Comment by Piiit** [comment]
@rcavaliere I will investigate
