### ISSUE TITLE
CI pipeline failing even before entering

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/webcomp-mobility-traffic#25]
See https://ci.opendatahub.bz.it/job/it.bz.opendatahub.webcomponents-webcomps/job/webcomp-mobility-traffic/view/change-requests/job/PR-24/2/console

**Comment by Piiit** [comment]
I will have a look now

**Comment by Piiit** [comment]
The pipeline failed because we did a CI jenkins update and removed all credentials from it, which were never supposed to be there for security reasons. The Ci pipeline of this web components uses now a fake credentials, and the pipeline works again.
