### ISSUE TITLE
Tagging of repo fails

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/webcomp-mobility-traffic#26]
Pipeline execution for tagging fails:
https://jenkins.testingmachine.eu/job/it.bz.opendatahub.webcomponents-webcomps/job/webcomp-mobility-traffic/

**Comment by etomsen** [comment]
Posso far qualcosa? Se fallisce il build, mi potresti girare il messaggio, perché in locale (appena controllato) non mi da nessun problema…
~Eugenio

**Comment by etomsen** [comment]
Dal messaggio vedo che manca il secret… magari ce qualcosa nel pipeline?

ERROR: webcomp-mobility-traffic_client-secret
Finished: FAILURE

**Comment by Piiit** [comment]
Hi, the pipeline fails because you added the dist-folder to the .gitignore file. We need the dist folder because we retrieve files that should be distributed through our CDN via git. So please do not exclude the folder cdn/noi...

**Comment by Piiit** [comment]
The build does not fail, just the push to git, because the newly build artifacts are excluded.

**Comment by etomsen** [comment]
Oh, oki. Sorry. Thought it was my mistake of not excluding them))
Will you make a change, or should I make another PR?

**Comment by Piiit** [comment]
I will make the change... I know that this approach does not follow the best practice of excluding build artifacts, but we use git as storage for those files...

**Comment by Piiit** [comment]
Done, lets wait for the crawler...
