### ISSUE TITLE
As a developer I would like that the Open Data Hub provides the geometries of the LinkStations as well

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#3]
This needs an extension of the current Open Data Hub API

**Comment by Piiit** [comment]
@rcavaliere Link to the user story https://github.com/noi-techpark/ninja/issues/4

**Comment by rcavaliere** [comment]
@Piiit will put the new end-point (LinkStations geometries) in production

**Comment by Piiit** [comment]
@rcavaliere @etomsen 
The new version is online, please test... any feedback welcome ;)

Example call:
https://mobility.api.opendatahub.bz.it/v2/flat,edge/LinkStation?where=egeometry.neq.null,eactive.eq.true
