### ISSUE TITLE
As an end-user I would like to have a consolidate comparison of the travel times between A22 and alternative roads

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#32]
It deals with the several configurations needed to have a final working prototype:
- [x] thresholds for defining congestion levels on the different road stretches
- [x] outlayer thresholds setting
- [x] complex LinkStations configurations (hardcoded alternatives to highway stretches)
- [x] Bluetooth Stations renaming
- [x] translations

**Comment by rcavaliere** [comment]
@bertolla the PR are immediately visible in the development branch?

**Comment by bertolla** [comment]
Do you mean the changes in development branch? I think Peter M. wanted to implement it. Beforehand it only worked with tags.

**Comment by Piiit** [comment]
@bertolla @rcavaliere Yes, I have started with this, but for now it is low priority... I will continue and add automation step by step...

**Comment by rcavaliere** [comment]
@Piiit ok, no problem! When you have time this week, can you integrate my PR for this web-component, so that I can check if they work properly?

**Comment by Piiit** [comment]
sure, I will ... but I do not see any PRs... have you pushed them to "development" already?

**Comment by rcavaliere** [comment]
Yes, since we don't have a production environment yet

**Comment by Piiit** [comment]
OK

**Comment by Piiit** [comment]
@rcavaliere Done.... See https://webcomponents.opendatahub.testingmachine.eu/webcomponent/ffe771ee-1786-11eb-adc1-0242ac120002

New Version is v0.5.0

**Comment by rcavaliere** [comment]
I can't finish test this until issue https://github.com/noi-techpark/bdp-commons/issues/229 is solved

**Comment by rcavaliere** [comment]
Some little issues to be fixed here in order to have first prototype yet, see #19 and #10

**Comment by etomsen** [comment]
@rcavaliere done. Plz check 2 pull requests

**Comment by rcavaliere** [comment]
Wonderful, super quick! @Piiit or @bertolla can you please integrate them?

**Comment by Piiit** [comment]
@rcavaliere Done, see v0.6.0 on https://webcomponents.opendatahub.testingmachine.eu/webcomponent/ffe771ee-1786-11eb-adc1-0242ac120002

**Comment by rcavaliere** [comment]
Still under testing, need to check this better with more normal traffic flows...
