### ISSUE TITLE
1st prototype implementation

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-traffic#6]
- [x] Implementation @etomsen 
- [x] Pipeline of the Web Component Store @Piiit @bertolla (+ add special script tags)
- [x] Bundling for the store @etomsen 
- [x] Bundle upload feature (store) @bertolla @Piiit 
> not directly via uploading a whole directory, but with a list of files inside the manifest file
- [x] CI integration (jenkins) @Piiit 
- [x] CD integration (internal jenkins) @Piiit 
- [x] Working preview for the store @Piiit @bertolla 
> This seems to be a problem of the store and not the web component, I will open a new issue for that... See https://github.com/noi-techpark/odh-web-components-store/issues/77
- [x] Final testing @rcavaliere 
> Please always test with the "EXTERNAL WINDOW" preview, since the internal preview does not work

**Comment by rcavaliere** [comment]
We agreed today to receive a 1st PR by 16.10, so that we can then integrate it in our testing environment the week after

**Comment by etomsen** [comment]
I've just made a first PR, plz review

**Comment by rcavaliere** [comment]
ok, thanks! @bertolla can you please integrate the PR and create a testing environment for this new web application?

**Comment by etomsen** [comment]
Plz close, when tested

**Comment by rcavaliere** [comment]
Next steps:
- [ ] @etomsen makes a new PR without dependancies
- [ ] @bertolla completes the pipeline and the deployment (@etomsen provides all necessary technical feedback)

**Comment by bertolla** [comment]
I've tried to setup PIpelines and have the first prototype running on the webcomponent store. A short
résumé:
- CI pipeline is now running on all branches. It tries to test and build  the project with the docker-container. I had to disable sandbox to be able to run tests in the docker container: 4ed05ae10c003dcac5192658775198d2cfbf1947
Tests are still failing, also locally, not just in the container.
![tests](https://user-images.githubusercontent.com/3582457/97183777-76c7a880-179e-11eb-90d0-83d8c6adb498.png)
- I adapted the wcs-manifest file for deployment to the store, build the project, as described in documentation and comitted the builded files. To make the building process work I had to disable failure on warnings 4ed05ae10c003dcac5192658775198d2cfbf1947. 

The webcomponent is up on the webcomponent store https://webcomponents.opendatahub.testingmachine.eu/, but not running.
I guess it depends on how stencil is packaging it. 

@etomsen Is there a way to have a single js file to include the webcomponent in a website?

**Comment by etomsen** [comment]
Hey!

Yes, i still need to fix tests, Ill commit tomorrow. Regarding the build
bundling... yes, sure, its possible to have all bundle in one file, but not
suggested as it will drammatically slow down the performance and increase
the first load (mainly because of leaflet maps).

In my example (indec.html) in the project, i include one file, and the rest
of the bundle is loaded dynamically from the build folder.

Can we do it this way, or we need to pack everything in one js?
Cheers, Eugene

**Comment by bertolla** [comment]
I hope it also works this way. I need to ask the guys of the webcomponent store and I'll give you feedback as soon as I know more.
Cheers,
Patrick

**Comment by etomsen** [comment]
@bertolla another thing I've noticed: you need also include css file for your web-component to function properly. I do it as following. plz also check how to host the assets, as we use some graphics inside the web-component (and .json translations files) that are loaded in async way. 
I do it as following (presuming my build dir is "/build"):
```
<script type="module" src="/build/noi-mobility-traffic.esm.js"></script>
 <script nomodule src="/build/noi-mobility-traffic.js"></script>
 <link rel="stylesheet" href="/build/noi-mobility-traffic.css">
 <noi-mobility-traffic lang="en"></noi-mobility-traffic>
```

**Comment by rcavaliere** [comment]
@bertolla @etomsen can we set up a first demo of the prototype at the beginning of the next week, so that I can have the time to test it before our next sprint meeting?

**Comment by bertolla** [comment]
I can make it run on a custom made website with no problems, but for the webcompstore it's another story. It depends, if it's even supporting bundle uploads and stylesheets outside the single js file

**Comment by rcavaliere** [comment]
@bertolla in the meantime that the issues with the webcomponents store are cleared, I would suggest to make it available in a custom website, e.g. in the BrennerLEC website (using the one you already used for testing)

**Comment by etomsen** [comment]
Hey @bertolla, can you pls check the latest PR (there is an index.html example with one file import and no CSS import). If it does not work I could try bundling the component files manually with webpack...

**Comment by etomsen** [comment]
@bertolla , @Piiit  To sum up the check that I've made on bundling, so it's all correct, stencil produces on build (nom run build) a list folder with contains several versions of the bundle divided into subfolders:
1) cjs - a version that uses common javascript modules for browsers like IE11 that don't support ESM modules
2) collection - a version to be used by other stencil apps
3) esm - a version that should be ok for most modern browsers 
4) noi-mobility-traffic - a fully furnished ESM build made specially for unpkg CDN it contains all the assets/translation files, etc.

So this is the one that we want to use. And this whole folder should be hosted. The entry point is following: dist/noi-mobility-traffic/noi-mobility-traffic.esm.js. The reason why index file is empty there is related to the import and described [here](https://github.com/ionic-team/stencil/issues/1840), so it's supposed to be so.

**Comment by Piiit** [comment]
@etomsen Thanks, cool recap... could you add this to the README so that we do not forget about it in the future? I have now also the CI ready, you should see it when you create a PR... please check if you are able to see the logs when you click on details. Patrick has a look at the store src in the meantime...

**Comment by Piiit** [comment]
@bertolla We have another problem with the CDN: It does not look into subfolders, when serving files

**Comment by Piiit** [comment]
@etomsen When I try to preview the file on the store with the following snippet:

```html
<noi-mobility-traffic style='--noi-font-family: "Roboto", "Helvetica Neue", sans-serif; 
                --noi-width: 100%;
                --noi-height: 100%;
                --noi-primary: #0068B4;
                --noi-primary-rgb: 0, 104, 180;
                --noi-primary-contrast: #ffffff;
                --noi-action-rgb: 87, 173, 57;
                --noi-action: #339966;
                --noi-action-contrast: #ffffff;' lang="en"></noi-mobility-traffic>
                <script type="module" src="https://cdn.webcomponents.opendatahub.testingmachine.eu/dist/ffe771ee-1786-11eb-adc1-0242ac120002/v0.3.0/noi-mobility-traffic.esm.js" data-stencil></script>
                <script nomodule src="https://cdn.webcomponents.opendatahub.testingmachine.eu/dist/ffe771ee-1786-11eb-adc1-0242ac120002/v0.3.0/noi-mobility-traffic.js"></script>
```

... it throws an error:

```
Uncaught SyntaxError: import declarations may only appear at top level of a module; See noi-mobility-traffic.esm.js:1
```

**Comment by etomsen** [comment]
@bertolla @Piiit hey, yes, I've figured it out now... I think I have the solution for the CDN. Could you plz give me the baseUrl? Should be `https://webcomponents.opendatahub.testingmachine.eu/webcomponent/ffe771ee-1786-11eb-adc1-0242ac120002`, right? where is the guid coming from?

**Comment by etomsen** [comment]
Guys @bertolla  @Piiit , I've just created a PR, plz check it. You should try to do `npm run build:cdn` after that, it should generate the `cdn` folder with all the files needed (including index.html). I've flattened the structure, so all the resources (json, images) are on the root level without subfolders. Plz take that generated index.html as an example of integration, it should have all paths properly configured. 

I've briefly tested it by copying all the content to local tomcat subfolder (localhost:8080/noi) and it looks ok. If this works, I'll update the readme file ;)

**Comment by Piiit** [comment]
@etomsen @bertolla I fixed several issues inside the store and introduced a new manifest > dist > scripts section, to upload all files inside the manifest > dist > files section, but only use the scripts list for the snippet. Strangely, it does not work for the iframe preview, but it works for the external window preview.

However, there sometimes the tiles are not loading completely. Please have a look at that, @etomsen... thanks
And maybe, you can also find the reason why it does not load inside the iframe.

**Comment by etomsen** [comment]
Hey @bertolla @Piiit yes, I've just checked it so,
1) regarding iframe: I've managed to run the web component correctly in my local tomcat instance using iframe without any issues with the following code of the iframe:
```
<html>
  <head></head>
  <body>
    <noi-mobility-traffic lang="en" style="--noi-font-family: 'Roboto', 'Helvetica Neue', sans-serif; --noi-width: 100%;--noi-height: 100%;--noi-primary: #0068B4;--noi-primary-rgb: 0, 104, 180;--noi-primary-contrast: #ffffff;--noi-action-rgb: 87, 173, 57;--noi-action: #339966;--noi-action-contrast: #ffffff;"></noi-mobility-traffic>
    <script type="module" src="./noi-mobility-traffic.esm.js"></script>
    <script nomodule="" src="./noi-mobility-traffic.js"></script>
  </body>
</html>
```

and the following index.html 
```
<html>
  <head></head>
  <body>
    <iframe height=400 width=400 src="./iframe.html" frameborder="0"></iframe>
  </body>
</html>
```
Maybe the reason is connected to the fact that you have unhandled exception on the page (RangeError: date value is not finite in DateTimeFormat format()) which prevents iframe loading? (At least I see it in console)

2) Regarding the tiles that are not loaded entirely, I think I've found this issue (which is connected to the ResizeObservable). I've just made a fix. Can't test it locally as it only happens in CDN, so plz check/approve the PR and let's see.

~Eugenio
